#!/usr/bin/env bash
# install.sh — one-line installer for email-platform
# Usage:  ./install.sh
# Remote: curl -fsSL https://raw.githubusercontent.com/mcdnew/email-platform/main/install.sh | bash
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()    { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*" >&2; exit 1; }
heading() { echo -e "\n${BOLD}$*${NC}"; }

# ── 0. Resolve script directory (works both locally and via curl | bash) ──────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" 2>/dev/null && pwd || pwd)"

# If piped through bash (curl | bash), download the repo as a zip (no git needed)
if [ ! -f "$SCRIPT_DIR/docker-compose.yml" ]; then
  heading "Downloading email-platform..."
  command -v curl >/dev/null 2>&1 || error "curl is required. Install it and re-run."
  command -v unzip >/dev/null 2>&1 || error "unzip is required. Install it (e.g. apt install unzip) and re-run."
  curl -fsSL https://github.com/mcdnew/email-platform/archive/refs/heads/main.zip -o /tmp/email-platform.zip
  rm -rf /tmp/email-platform-extract
  unzip -q /tmp/email-platform.zip -d /tmp/email-platform-extract
  rm -rf email-platform
  mv /tmp/email-platform-extract/email-platform-main email-platform
  rm -rf /tmp/email-platform.zip /tmp/email-platform-extract
  cd email-platform
  SCRIPT_DIR="$(pwd)"
else
  cd "$SCRIPT_DIR"
fi

heading "Email Platform Installer"
echo "Working in: $(pwd)"

# ── 1. Check Docker ───────────────────────────────────────────────────────────
heading "Checking prerequisites..."

command -v docker >/dev/null 2>&1 || error "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
docker info >/dev/null 2>&1       || error "Docker daemon is not running. Start Docker and re-run."

# Detect compose command (v2 plugin or standalone)
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  error "Docker Compose not found. Install it from https://docs.docker.com/compose/install/"
fi

info "Docker: $(docker --version)"
info "Compose: $($COMPOSE version)"

# ── 2. Create .env if missing ─────────────────────────────────────────────────
heading "Configuring environment..."

if [ -f .env ]; then
  warn ".env already exists — skipping. Edit it manually to change settings."
else
  echo "A few questions to set up your .env file."
  echo "(Press Enter to accept the default shown in brackets)"
  echo ""

  # API key
  read -rp "  API key for the admin UI (leave blank to disable auth for local dev): " API_KEY
  API_KEY="${API_KEY:-}"

  # Postgres password (required — no default)
  while true; do
    read -rsp "  PostgreSQL password (required): " POSTGRES_PASSWORD
    echo ""
    [ -n "$POSTGRES_PASSWORD" ] && break
    warn "Password cannot be empty."
  done

  # SMTP
  echo ""
  echo "  SMTP settings (needed to actually send emails — you can update these later):"
  read -rp "  SMTP server   [smtp.gmail.com]: "   SMTP_SERVER;   SMTP_SERVER="${SMTP_SERVER:-smtp.gmail.com}"
  read -rp "  SMTP port     [587]: "               SMTP_PORT;     SMTP_PORT="${SMTP_PORT:-587}"
  read -rp "  SMTP username [your@email.com]: "   SMTP_USER;     SMTP_USER="${SMTP_USER:-your@email.com}"
  read -rsp "  SMTP password: "                    SMTP_PASSWORD; echo ""

  # Tracking base URL (optional)
  read -rp "  Public URL for open/click tracking (e.g. https://yourdomain.com, or blank to skip): " TRACKING_BASE_URL

  # Unsubscribe secret
  UNSUBSCRIBE_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom 2>/dev/null | head -c 32 || echo "change-me-$(date +%s)")

  cat > .env <<EOF
# Generated by install.sh — edit as needed

# Auth
API_KEY=${API_KEY}

# PostgreSQL
POSTGRES_USER=email_user
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=email_platform

# SMTP
SMTP_SERVER=${SMTP_SERVER}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}

# Tracking
TRACKING_BASE_URL=${TRACKING_BASE_URL}
UNSUBSCRIBE_SECRET=${UNSUBSCRIBE_SECRET}

# Scheduler
MAX_EMAILS_PER_DAY=200
MAX_RETRIES=3
EOF

  info ".env created."
fi

# ── 3. Build and start ────────────────────────────────────────────────────────
heading "Building containers (this takes a minute the first time)..."
$COMPOSE build --quiet

heading "Starting services..."
$COMPOSE up -d

# ── 4. Wait for Postgres to be ready ─────────────────────────────────────────
heading "Waiting for database..."
MAX_WAIT=30
WAITED=0
until $COMPOSE exec -T db pg_isready -U email_user -q 2>/dev/null; do
  sleep 1
  WAITED=$((WAITED + 1))
  [ $WAITED -ge $MAX_WAIT ] && error "Database did not become ready after ${MAX_WAIT}s. Check: $COMPOSE logs db"
done
info "Database is ready."

# ── 5. Run migrations ─────────────────────────────────────────────────────────
heading "Running database migrations..."
$COMPOSE exec -T backend alembic upgrade head
info "Migrations applied."

# ── 6. Done ───────────────────────────────────────────────────────────────────
heading "Done!"
echo ""
echo -e "  ${BOLD}Frontend:${NC} http://localhost:3000"
echo -e "  ${BOLD}Backend:${NC}  http://localhost:8000/docs"
echo ""
echo "Useful commands:"
echo "  $COMPOSE logs -f          # tail all logs"
echo "  $COMPOSE logs -f backend  # tail backend only"
echo "  $COMPOSE down             # stop everything"
echo "  $COMPOSE pull && $COMPOSE up -d --build  # update to latest"
echo ""
