"""Initial schema

Revision ID: 5709abcc18d4
Revises: 
Create Date: 2025-07-11 19:07:31.834989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel     # ← add this so `sqlmodel.sql.sqltypes.AutoString` is defined


# revision identifiers, used by Alembic.
revision: str = '5709abcc18d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailtemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bcc_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unsubscribed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequencestep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['emailtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduledemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['emailtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentemail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('sequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['emailtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentemail')
    op.drop_table('scheduledemail')
    op.drop_table('sequencestep')
    op.drop_table('prospect')
    op.drop_table('sequence')
    op.drop_table('emailtemplate')
    # ### end Alembic commands ###
